### PR TITLE
That should be a + != :

### PR DESCRIPTION
**Pull request by Orion116**
A member on the BrokenOS team mentioned this, haha

### CODE REVIEW

**Comment by Joshndroid** [comment]
i have already fixed it bro - https://github.com/Joshndroid/android_device_samsung_lt03wifi/commit/aac61d711d9e791e053754f3fe51a6cfadeb9cc4

**Comment by Orion116** [comment]
I didn't see the change?

**Comment by Joshndroid** [comment]
i then pushed to shevt and he ended up doing this - https://github.com/ShevT/device_samsung_lt033g/commit/0b8ebce3fa022dc675fb091ab64a6fc7f9b5ec46

**Comment by Joshndroid** [comment]
im probably going to revert mine and do that change... just havnt had time... i wanted it to be consolidated but if i play with anything else it will make potential merges later harder... I did it originally in that way to eliminate stuff 1 by 1 to ensure that the issue was fixed. Keep your fix and as i said ill change mine back

**Comment by Orion116** [comment]
OK.  I may also revert mine too, since that is similar to mine.

**Comment by Joshndroid** [comment]
if u now sync mine i have reverted and fixed it

**Comment by Orion116** [comment]
Yeah I will cherry-pick it later :+1:

**Pull request closed without merging**
